[package]
name = "arti-hyper-connector"
version = "0.1.0"
edition = "2024"

[dependencies]
arti-client = "0.33.0"
http = "1.3.1"
hyper-util = { git = "https://github.com/sjcobb2022/hyper-util", version = "0.1.16", features = ["client", "client-legacy", "tokio", "http1", "http2"] }
thiserror = "2.0.15"
tokio = "1.47.1"
tor-rtcompat = "0.33.0"
tower-service = "0.3.3"
